// react-typescript/src/pages/app.tsx
import React from 'react';

import logo from '@/assets/imgs/logo.png';

import './app.scss';

const App: React.FunctionComponent = () => {
  return (
    <div className="container">
      <img src={logo} className="logo" />
      <p className="welcome">React TypeScript</p>
    </div>
  );
};

export default App;

// vue-test-lint/src/pages/App.vue
<template>
  <div class="container">
    <img :src="logo" alt="Logo" />
    <welcome :text="text" />
  </div>
</template>

<style lang="scss">
.container {
  text-align: center;
  padding-top: 100px;
}
</style>

<script>
import logo from "../assets/imgs/vue.png";

import Welcome from "../components/welcome.vue";

export default {
  components: {
    Welcome
  },
  data() {
    return {
      logo,
      text: "Hello World!"
    };
  }
};
</script>
