// vue-start/src/pages/app.vue
<template>
  <div class="container">
    <img
      :src="logo"
      alt="Logo"
    >
    <h1>Hello World!</h1>
  </div>
</template>

<style lang="scss">
.container {
  text-align: center;
  padding-top: 100px;
}
</style>

<script>
import logo from '@/assets/imgs/vue.png';

export default {
  data() {
    return {
      logo
    };
  }
};
</script>

// packages/react-lib/example/pages/app.jsx
import React from 'react';

import { TestComponent } from '@/index';

import logo from '../assets/imgs/logo.png';

import './app.scss';

const App = () => {
  return (
    <div className="container">
      <img src={logo} className="logo" />

      <div>
        <TestComponent label="Hello World!" />
      </div>
    </div>
  );
};

export default App;
