// vue-app/src/pages/sso.vue
﻿<template>
  <div id="page-sso"></div>
</template>

<script>
import { Toast } from 'vant';

import config from '@/config';
import { USER_MUTATIONS_SET_USER } from '@/store';

export default {
  name: 'page-sso',
  created() {
    // 单点登录
    this.ssoLogin();
  },
  methods: {
    getUser() {
      return new Promise((resolve) => {
        if (config.env === 'development') {
          resolve(config.testUser);
          return;
        }
        // DO SOMETHING
      });
    },
    ssoLogin() {
      this.$store.commit(USER_MUTATIONS_SET_USER, null);
      const { returnUrl = '/' } = this.$route.query;

      const toast = Toast.loading({
        message: '自动登录中...',
        forbidClick: true,
        duration: 0,
      });

      // 调用原生接口获取用户信息
      this.getUser()
        .then((res) => {
          const { userCode, userName, tokenId } = res;

          this.$store.commit(USER_MUTATIONS_SET_USER, {
            tokenId,
            userCode,
            userName,
          });
          Toast.clear();
          this.$router.replace(decodeURIComponent(returnUrl));
        })
        .catch(() => {
          Toast.fail({
            message: '自动登录失败',
            forbidClick: true,
            duration: 2000,
          });
        });
    },
  },
};
</script>

<style lang="scss" scoped>
.page-sso {
}
</style>

// react-app/src/pages/sso.tsx
import React from 'react';
import { withRouter, RouteComponentProps } from 'react-router-dom';
import { connect } from 'react-redux';

import { Loading } from '@/components';
import native from '@/common/lib/native';
import { IStoreState, IUserState, IUser, setUser } from '@/store';

import './sso.scss';

export interface IProps extends RouteComponentProps {
  userState: IUserState;
  setUser: (user: IUser) => void;
}

const Page: React.FC<IProps> = (props) => {
  const { history, location, userState, setUser } = props;

  const searchParams = new URLSearchParams(location.search);

  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    native
      .getUser()
      .then((res) => {
        const { userCode, userName, tokenId } = res;

        setTimeout(() => {
          if (!userState.user) {
            setUser({
              tokenId,
              userCode,
              userName,
            });
            history.replace(
              decodeURIComponent(searchParams.get('returnUrl') || '/')
            );
          }
        }, 300);
      })
      .catch(() => {
        setLoading(false);
      });
  }, []);

  return <Loading fullScreen={true} message="自动登录中" />;
};

const mapStateToProps = (state: IStoreState) => ({
  userState: state.user,
});

const mapDispatchToProps = (dispatch) => ({
  setUser: (user: IUser) => dispatch(setUser(user)),
});

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(Page));
